### ISSUE TITLE
Unable to click on repository links on iOS 17 and MacOS Safari 17.4.1

### ISSUE THREAD

**Issue by eltigerchino** [colinlienard/githundred#6]
I first browsed the site on my iPhone and thought there weren't any links. Then, I proceeded to open the same site on my macbook from Safari. When I looked at this repo's code I finally noticed there was already a link. So, I tried opening the site in a Chromium browser and it works as expected.

The anchor tag exists even in Safari ~so I'm not sure why the element is not recognised as a link and is not clickable.~ but something's wrong with Safari's CSS so the table head is blocking the interaction with the anchor tag.

In the image below, I'm hovering over the table body row with the dev tool inspector but it selects the table head instead.
![CleanShot 2024-05-23 at 11  44 33@2x](https://github.com/colinlienard/githundred/assets/54401897/561a8404-2887-44a5-8da0-0f0ee8b25686)

EDIT: The issue seems to stem from these two absolute positioned content blocking the link interaction
https://github.com/colinlienard/githundred/blob/92abe5e12c1f1fea411b202a1e3fb5950e96e955/pages/index.vue#L128
https://github.com/colinlienard/githundred/blob/92abe5e12c1f1fea411b202a1e3fb5950e96e955/pages/index.vue#L145-L152

**Comment by colinlienard** [comment]
I hate safari 😅
Thanks for pointing this out, it should be fixed now
